#!/usr/bin/env bash
#display numbers from 1 to 100
#display FizzBuzz when the number is a multiple of 3 and 5
#display Buzz when the number is a mutiple of 3
#otherwise, display the number
#In a list format

((n=1))
while [ $n -le 100 ]; do 

	if [ $((n%3)) -eq 0 ] && [ $((n%5)) -eq 0 ]; then
		echo "FizzBuzz"

	elif [ $((n%3)) -eq 0 ]; then 
		echo "Fizz"

	elif [ $((n%5)) -eq 0 ]; then
		echo "Buzz"

	else
		echo "$n"
	fi

	((n++))
done
