#!/usr/bin/env bash
#Bad luck
counter=1
while ((counter<=20))
do
	case $counter in
	
		4)
			echo "$counter"
			echo "bad luck from China"
			;;
		9)
			echo "$counter"
			echo "bad luck from Japan"
			;;
		17)
			echo "$counter"
			echo "bad luck from Italy"
			;;
		*)
			echo "$counter"
			;;
		esac
		((counter++))
done
© 2022 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
