#!/usr/bin/env bash
#Information about the school file

#Check if the school file exists
if [ -e school ];
       echo "School file exists"

        #Check if the school file exists or not
        if [ -s school ]; then 
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	#Check if it's a regular file
	if [ -f school ]; then
		echo "school is a regular file"

	fi

#File does not exist
else 	
	echo "school file does not exist"
