#!/usr/bin/env bash
#Create the file /var/run/myscript.pid containing its PID
#Display To infinity and beyond indefinitely
#Display I hate kill command when receiving a SIGTERM signal
#Display Y U no love me?! when receiving a SIGINT signal
#Delete the file /var/run/myscript.pid
#Terminates itself when receiving a SIGQUIT or SIGTERM signal

echo $$ > /var/run/myscript.pid
while true
do 
	echo "To infinity and beyond"
	sleep 2
	
	trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT
done
