#!/usr/bin/env bash
#A Bash script that displays To infinity and beyond indefinitely
#with sleep 2 in between of each iteration of the loop

while true
do
        echo "To inifinity and beyond"
        sleep 2

done
